language: generic
dist: xenial
os: linux

services:
  - docker

before_install:
  - docker build -t ghozt81nl/dockermulticicdclient -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ghozt81nl/dockermulticicdclient npm run test

after_success:
  - docker build -t ghozt81nl/dockermulticicdclient:v5 ./client
  - docker build -t ghozt81nl/dockermulticicdapi:v5 ./api
  - docker build -t ghozt81nl/dockermulticicdnginx:v5 ./nginx
  - docker build -t ghozt81nl/dockermulticicdworker:v5 ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ghozt81nl/dockermulticicdclient:v5
  - docker push ghozt81nl/dockermulticicdapi:v5
  - docker push ghozt81nl/dockermulticicdnginx:v5
  - docker push ghozt81nl/dockermulticicdworker:v5