language: generic
dist: xenial
os: linux

services:
  - docker

before_install:
  - docker build -t ghozt81nl/dockermulticicdclient -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ghozt81nl/dockermulticicdclient npm run test

after_success:
  - docker build -t ghozt81nl/dockermulticicdclient ./client
  - docker build -t ghozt81nl/dockermulticicdapi ./api
  - docker build -t ghozt81nl/dockermulticicdnginx ./nginx
  - docker build -t ghozt81nl/dockermulticicdworker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ghozt81nl/dockermulticicdclient
  - docker push ghozt81nl/dockermulticicdapi
  - docker push ghozt81nl/dockermulticicdnginx
  - docker push ghozt81nl/dockermulticicdworker

deploy:
  provider: elasticbeanstalk
    region: "eu-west-1"
    app: "Docker-Multi"
    env: "DockerMulti-env"
    bucket: "elasticbeanstalk-eu-west-1-011444914508"
    bucket_path: "docker-multi"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
        branch: master
